### ISSUE TITLE
Resize grapples not updated after undo/redo

### ISSUE THREAD

**Issue by kinimesi** [iVis-at-Bilkent/cytoscape.js-node-resize#14]
Move a node inside a compound and then select that compound. Press undo and then redo. After redo operation grapples are not refreshed. See the image below.
![screen shot 2017-06-12 at 02 29 25](https://user-images.githubusercontent.com/7281872/27015484-3edc13be-4f17-11e7-8da0-ec333002ce72.png)

**Comment by royludo** [comment]
This particular issue is solved, but the same problem is happening when moving a node in and out of a compound and undo/redo that. But this issue was already there I think (at least on the master branch of newt). 
It is linked to a deeper problem. When restoring elements (after an undo/redo for example), no event is triggered. Add/remove events are part of how we detect parent change. But when restoring it gets impossible to react to that. Maybe we should trigger an 'add' event when restoring an element. Or maybe there should be a changeParent event triggered somewhere.
Because in the end, changing an element's parent isn't the same as just removing and adding a node.

**Comment by kinimesi** [comment]
@royludo Looks like not that deeper after all. Listening for undo/redo events and updating drawing is enough.

**Comment by kinimesi** [comment]
@royludo can you verify and close the issue? Thanks.

**Comment by royludo** [comment]
Ha, I didn't think about that. Thanks.

**Comment by royludo** [comment]
There is still some issue in fact.

Select a compound. Move one child outside of it. Undo. Then move that same child out again. Grapples are not updated.
